---
title: "Water Right Diversions - Data Exploration"
author: "Maddee Rubenson (FlowWest)"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(leaflet)
library(sf)
```

Data Dictionary: https://waterrightsmaps.waterboards.ca.gov/viewer/Resources/Images/eWRIMS/download/POD_data_dictionary.pdf


https://gispublic.waterboards.ca.gov/portal/home/item.html?id=746870b4aa1f47579ca1bf5d6c9924a8

```{r include=FALSE}
# Water rights data ###########################################################
wrims_raw <- read_csv(here::here("data-raw", "rms_diversion_2024.csv")) # water use report for water rights

ewrims_gdb <- here::here('data-raw', 'shapefiles','eWRIMS_Data.gdb') # points of diversion map
ewrims <- st_read(ewrims_gdb) 
st_layers(ewrims_gdb)
ewrims_pod_raw <- st_read(ewrims_gdb, layer = "Points_of_Diversion_20250301")
ewrims_pod <- ewrims_pod_raw |> 
  st_transform(crs = "+proj=longlat +datum=WGS84") |> 
  st_zm() |> 
  filter(!is.na(LATITUDE), !is.na(LONGITUDE))  |> 
  left_join(wrims_raw |> 
              rename(APPL_ID = APPLICATION_NUMBER) |> 
              select(APPL_ID, PRIMARY_OWNER_NAME, FACE_VALUE_OR_REPORTED_VALUE)) |> 
  filter(!is.na(FACE_VALUE_OR_REPORTED_VALUE))
```


```{r eval=FALSE, include=FALSE}
DT::datatable(ewrims_pod, options = list(
                  scrollX = TRUE,  
                  pageLength = 10 
                ))
```

Map shows top 10% of water right diversion totals 

```{r echo=FALSE}
ewrims_top10 <- ewrims_pod |> 
    filter(FACE_VALUE_OR_REPORTED_VALUE >= quantile(FACE_VALUE_OR_REPORTED_VALUE, 0.9, na.rm = TRUE))

pal <- colorNumeric(palette = "Blues", domain = ewrims_top10$FACE_VALUE_OR_REPORTED_VALUE)

leaflet(data = ewrims_top10) |> 
  addTiles() |> 
  addCircleMarkers(data = ewrims_top10,
                   # ~longitude, ~latitude,
                   fillColor = ~pal(FACE_VALUE_OR_REPORTED_VALUE),
                   color = ~pal(FACE_VALUE_OR_REPORTED_VALUE),
                   radius = 1,
                   #radius = ~sqrt(FACE_VALUE_OR_REPORTED_VALUE) ,
                   opacity = 1, 
                   fillOpacity = 0.8,
                   popup = ~paste(
                     "<strong>ID:</strong>", APPL_ID, "<br>",
                     "<strong>Primary Owner:</strong>", PRIMARY_OWNER_NAME, "<br>",
                     "<strong>Face or Reported Value:</strong>", FACE_VALUE_OR_REPORTED_VALUE
                   )) |> 
  addLegend(position = "bottomright", 
            pal = pal, 
            values = ~FACE_VALUE_OR_REPORTED_VALUE, 
            title = "Face or Reported Value", 
            opacity = 1)


```

Exploring total allotments by primary owner type and number of allotments each owner type has

```{r, echo = FALSE}
ewrims_top10 |> 
  group_by(PRIMARY_OWNER_NAME) |> 
  summarise(total_allotment = sum(FACE_VALUE_OR_REPORTED_VALUE),
            n = n()) |> 
  arrange(desc(total_allotment)) |> 
  st_drop_geometry() |> 
  DT::datatable()

```

### Format data for dashboard 

```{r}
ewrims_clean <- ewrims_pod |> 
  mutate(FACE_VALUE_OR_REPORTED_VALUE = round(FACE_VALUE_OR_REPORTED_VALUE, 0)) |> 
  filter(FACE_VALUE_OR_REPORTED_VALUE > 0) |> 
  mutate(beneficiary_type = "Water right owner") |> 
  mutate(quantity_unit = "acre-feet") |> 
  select(beneficiary_type, 
         entity_name = PRIMARY_OWNER_NAME, , 
         entitity_contact = APPL_ID,
         latitude = LATITUDE, 
         longitude = LONGITUDE,
         quantity_metric = FACE_VALUE_OR_REPORTED_VALUE, 
         quantity_unit,
         geometry = SHAPE, 
         entity_address = HU_12_NAME) |> # unsure if we want this for the address, but it's the closest I can think of   
  mutate(entitity_contact = paste0("Parcel Number: ", entitity_contact)) |> 
  glimpse()

# TODO: do we want to limit the water rights since there are so many and small (median 48)
ggplot(ewrims_clean, aes(x = quantity_metric)) + 
  geom_histogram(bins = 30)

summary(ewrims_clean$quantity_metric)

saveRDS(ewrims_clean, here::here("data-raw", "water_rights_clean.RDS"))

```

