---
title: "Data Exploration - CA Drinking Water Systems "
author: "Badhia Yunes Katz / Ashley Vizek"
date: "April 18, 2025"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.width=15, fig.height=10)
library(leaflet)
library(sf)
library(tidyverse)
library(janitor)
```

# Summary

There are 4 relevant datasets to understanding public water systems:

1. [Drinking water system area boundaries](https://gispublic.waterboards.ca.gov/portal/home/item.html?id=fbba842bf134497c9d611ad506ec48cc)

2. [Drinking water source facility locations](https://data.cnra.ca.gov/dataset/urban-water-data-drought/resource/9688aeb1-6c77-44aa-9cf7-6b1c1306f399).

3. [Water supply and demand](https://data.ca.gov/dataset/drinking-water-public-water-system-annually-reported-water-production-and-delivery-information-2013/resource/ddac281d-4f71-45ba-99bd-394fa33d0e58).

4. [Urban water retailer demand](https://data.ca.gov/dataset/urws-conservation-supply-demand).

# Overview 

This markdown will only pull the [Drinking water system area boundaries](https://gispublic.waterboards.ca.gov/portal/home/item.html?id=fbba842bf134497c9d611ad506ec48cc) data, to do initial National Forest relationship 

```{r include=FALSE}
# drinking water system boundaries #############################################
dw_system_boundaries <- st_read("data-raw/drinking_water_systems/California_Drinking_Water_System_Area_Boundaries.shp") |> 
  st_transform(crs = "+proj=longlat +datum=WGS84") |> 
  clean_names()
```


```{r eval=FALSE, include=FALSE}
leaflet(dw_system_boundaries) |>
  addTiles() |>
  addPolygons()
```


```{r echo=FALSE}
# reading watersheds to clip dws
# watersheds <- readRDS(here::here("data", "watersheds.RDS")) |>
#   st_make_valid() |> 
#   st_transform(4326)  
# 
# dw_system_boundaries <- dw_system_boundaries |>
#   st_make_valid() |> 
#   st_transform(4326)
# 
# # clipping drinking water systems to watersheds of interest
# dws_norcal <- st_intersects(dw_system_boundaries, watersheds)
# dws_norcal_sf <- dw_system_boundaries[selected, ]
# 
# dws<- dws_norcal_sf |> 
#   mutate(beneficiary_type = "drinking water system",
#          national_forest_connection = NA,
#          entity_name = WATER_SY_1,
#          entity_address = ADDR_LINE_,
#          entity_contact = AC_PHONE_N,
#          quantity_metric = NA,
#          quantity_unit = NA) |> 
#   select(beneficiary_type, national_forest_connection, entity_name, entity_address, entity_contact, quantity_metric, quantity_unit) |> 
#   glimpse()
# 
# # plotting
# leaflet(dws) |>
#   addTiles() |>
#   addPolygons()

```

```{r}
dw_system_boundaries <- dw_system_boundaries |>
  st_make_valid() |>
  st_transform(4326)
dw_system_boundaries <- st_centroid(dw_system_boundaries)

leaflet(dw_system_boundaries) |>
  addTiles() |>
  addCircles()

```
```{r}

water_beneficiaries_project_board <- pins::board_s3(bucket = "water-beneficiaries", region = "us-east-1")

ear_filtered_water_demand <- water_beneficiaries_project_board |> 
  pins::pin_read("ear_filtered_water_demand")

# water_demand_uws_raw is from: https://data.ca.gov/dataset/urws-conservation-supply-demand
water_demand_uws_raw <- read_csv("data-raw/drinking_water_systems/clearinghouse_report.csv")
water_demand_uws <- water_demand_uws_raw |> 
  janitor::clean_names() |> 
  rename(pwsid = water_system_id) |> 
  mutate(year = year(report_period_start_date),
         month = month(report_period_start_date)) |> 
  filter(year %in% c(2020:2024)) |> 
  group_by(pwsid, month) |> 
  summarize(potable_supply_gal = mean(potable_supply_minus_sold_gal, na.rm = T)) |> 
  ungroup() |> 
  group_by(pwsid) |> 
  summarize(potable_supply_gal = sum(potable_supply_gal))

water_demand <- ear_filtered_water_demand |> 
  janitor::clean_names() |> 
  group_by(pwsid, month) |> 
  summarise(quantity_delivered_gallons = mean(calculated_quantity_in_gallons, na.rm = T)) |> 
  ungroup() |> 
  group_by(pwsid) |> 
  summarize(quantity_delivered_gallons = sum(quantity_delivered_gallons, na.rm = T)) |> 
  full_join(water_demand_uws) |> 
  mutate(demand_gallons = ifelse((!is.na(potable_supply_gal) & potable_supply_gal >= 0), potable_supply_gal, quantity_delivered_gallons)) |> 
  select(pwsid, demand_gallons)

# There are some errors here. Assume that LA and EBMUD will have high demand but
# others will not
la_pwsid <- filter(ear_filtered_water_demand, grepl("LOS ANGELES", `Water.System.Name`)) |>  distinct(PWSID)
la_pwsid <- la_pwsid$PWSID
ebmud <- "CA0110005"
water_demand_clean <- water_demand |> 
  mutate(demand_gallons = case_when(!pwsid %in% c(la_pwsid, ebmud) & demand_gallons >= 9.328407e+10 ~ NA,
                                    T ~ demand_gallons))
  

dw_system_demand <- left_join(dw_system_boundaries |> 
                                 rename(pwsid = sabl_pwsid), water_demand_clean)
#TODO note that this data will then be joined to geospatial source, just pulling it as a placeholder for now to
# obtain the quantity metric
```
```{r}
dws<- dw_system_demand |>
  mutate(beneficiary_type = "drinking water system",
         national_forest_connection = NA,
         entity_name = water_sy_1,
         entity_address = addr_line,
         entity_contact = ac_phone_n,
         quantity_metric = demand_gallons,
         quantity_unit = "gallons") |>
  select(beneficiary_type, national_forest_connection, entity_name, entity_address, entity_contact, quantity_metric, quantity_unit) |>
  glimpse()
```


```{r}
# dws<- dw_system_boundaries |>
#   mutate(beneficiary_type = "drinking water system",
#          national_forest_connection = NA,
#          entity_name = water_syst,
#          entity_address = addr_line,
#          entity_contact = ac_phone_n,
#          quantity_metric = NA,
#          quantity_unit = NA) |>
#   select(beneficiary_type, national_forest_connection, entity_name, entity_address, entity_contact, quantity_metric, quantity_unit) |>
#   glimpse()
```

Save RDS
```{r}
saveRDS(dws, here::here('data', 'drinking_water_boundaries.RDS'))
```

